version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      ".env.docker"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/auxiliar_terapeutico
    ports:
      - "3000:3000"
    env_file:
      ".env.docker"
    tty: true
    stdin_open: true
    depends_on:
      - db
